finallyis keyword optional end part thetryblock . The code inside finally block always execute . This also true case exception even executedreturnstatement try block . Three thing happen try block . First , exception throw : You see pass thetryblock , execute thefinallyblock continue execution . Now , caught exception throw : We pass thetryblock exception occur , execute matchingcatchblock , thefinallyblock continue execution . Now , uncaught exception throw : We pass thetryblock exception occur execute thefinallyblock.NO CODEafter try-catch block execute . If exception happen try-catch block , thefinallyblock execute . Ifreturnstatement use inside finally , override return statement try-catch block . For instance , construct return 12 , 11 . Professional code almost never contain statement alter execution order ( likereturn , break , continue ) inside finally block , code difficult read maintain .