See alsoThrowing Catching Exceptions . Thetry-catchblocks use catch exception throwable object within code . Here 's whattry-catchblocks look like : try { statement1.1statement1.2 ... statement1.n } catch ( exception1 ) { statement2.1 ... statement2.n } Thecode list 3.6tries print argument pass program . However , enough argument , throw exception . In addition try catch block , afinallyblock may present . The finally block always execute , even exception throw . It may appear without catch block , always try block . Here finally block look like : try { statement1.1statement1.2 ... statement1.n } catch ( exception1 ) { statement2.1 ... statement2.n } finally { statement3.1 ... statement3.n }