By default , exception throw , current method interrupt , call method interrupt till themainmethod . A thrown exception also catch use atry/catchstatement . Below atry/catchstatement work : The executed code line highlight . When exception throw , method flow execute thetrystatement thecatchstatement . As thrown exception line 5 , line 6 execute , exception catch thecatchstatement thecatchblock execute . The following code also execute . Note thecatchstatement take exception parameter . There third case : exception class parameter : It notry/catchstatement . The exception throw call method .